import QueryProvider from './provider';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import './globals.css';
import { Provider } from 'jotai';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import type { Metadata } from 'next';
import { gothic_a1 } from './styles/font';

export const metadata: Metadata = {
  title: '뭔말이지?',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={gothic_a1.className}>
        <Provider>
          <QueryProvider>
            <Header />
            <ToastContainer />
            {children}
            <Footer />
          </QueryProvider>
        </Provider>
      </body>
    </html>
  );
}
