import QueryProvider from './provider';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import './globals.css';
import { Inter } from 'next/font/google';
import { Provider } from 'jotai';

import type { Metadata } from 'next';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: '뭔말이지?',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Provider>
        <QueryProvider>
          <Header />
          {children}
          <Footer />
        </QueryProvider>
      </Provider>
      </body>
    </html>
  );
}
